apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-react
  template:
    metadata:
      labels:
        app: hello-world-react
    spec:
      containers:
      - name: hello-world-react
        image: raghavd007/hello-world-react:latest
        ports:
        - containerPort: 3000
